# Generated by Django 4.1.7 on 2024-02-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0026_deliverydatecead_fvcicimporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeNacp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=512, verbose_name='Тип документа')),
                ('enabled', models.BooleanField(default=False, help_text='Незалежно від значення поля, представники НАЗК зможуть завантажувати документи лише опублікованих ОПВ', verbose_name='Дозволено для завантаження')),
                ('obj_types', models.ManyToManyField(to='search.objtype', verbose_name="Тип об'єкта")),
            ],
            options={
                'verbose_name': 'Тип документа (НАЗК)',
                'verbose_name_plural': 'Типи документів (НАЗК)',
                'db_table': 'cl_document_types_nacp',
            },
        ),
    ]
