# Generated by Django 2.1.3 on 2019-07-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0013_auto_20190426_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='Дані у форматі JSON')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.IpcAppList', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Відкриті дані',
                'verbose_name_plural': 'Відкриті дані',
            },
        ),
    ]
