# Generated by Django 2.1.3 on 2020-01-31 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20191010_1350'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='last_update',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='opendata',
            name='obj_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.ObjType'),
        ),
    ]
