# Generated by Django 2.1.3 on 2020-01-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200131_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='registration_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
