# Generated by Django 2.1.3 on 2020-01-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_opendata_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='app_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opendata',
            name='registration_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
