# Generated by Django 2.1.3 on 2020-02-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200206_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendata',
            name='app_number',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='last_update',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='registration_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='registration_number',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
