# Generated by Django 2.1.3 on 2020-02-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200206_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendata',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=32, null=True),
        ),
    ]
