# Generated by Django 2.1.3 on 2020-06-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200207_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='obj_state',
            field=models.PositiveSmallIntegerField(db_index=True, default=2),
        ),
    ]
