# Generated by Django 2.1.3 on 2020-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_opendata_obj_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='app_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
