# Generated by Django 2.2.17 on 2021-03-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_opendata_app_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='app_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='obj_state',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='registration_number',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
