# Generated by Django 2.2.17 on 2021-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210331_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='data_docs',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Стан діловодства у форматі JSON'),
        ),
    ]
