# Generated by Django 2.2.24 on 2021-09-02 10:50

import sys

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_opendata_data_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDataViewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.IntegerField(db_column='app_id')),
                ('data', models.TextField(verbose_name='Дані у форматі JSON')),
                ('data_docs', models.TextField(blank=True, default=None, null=True, verbose_name='Стан діловодства у форматі JSON')),
                ('data_payments', models.TextField(blank=True, default=None, null=True, verbose_name='Платежі, збори')),
                ('obj_type', models.IntegerField(blank=True, null=True, default=None, db_column='obj_type_id')),
                ('obj_state', models.PositiveSmallIntegerField(default=2)),
                ('last_update', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('app_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('app_date', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('registration_number', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('registration_date', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'opendata_api_view',
                'managed': 'test' in sys.argv,
            },
        ),
    ]
