# Generated by Django 2.2.24 on 2021-12-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_opendataviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='data_payments',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Платежі, збори'),
        ),
    ]
