# Generated by Django 2.2.24 on 2021-12-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_opendata_data_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendata',
            name='data',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Дані у форматі JSON'),
        ),
    ]
