# Generated by Django 4.1.7 on 2023-03-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230210_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenDataViewModel',
        ),
        migrations.RemoveField(
            model_name='opendata',
            name='is_visible',
        ),
    ]
