# Generated by Django 4.1.7 on 2023-08-30 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_opendataviewmodel_remove_opendata_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=1024, verbose_name='Найменування особи')),
                ('open_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.opendata')),
            ],
            options={
                'verbose_name': 'Особа',
                'verbose_name_plural': 'Особи',
            },
        ),
    ]
