# Generated by Django 4.1.7 on 2024-03-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
