# Generated by Django 2.1.3 on 2019-09-05 13:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(default='Контакти', max_length=255, verbose_name='Заголовок сторінки (укр.)')),
                ('title_en', models.CharField(default='Contacts', max_length=255, verbose_name='Заголовок сторінки (en.)')),
                ('content_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Зміст (укр.)')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Зміст (en.)')),
                ('admin_email_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email адміністратора (для відображення) 1')),
                ('admin_email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email адміністратора (для відображення) 2')),
                ('admin_email_3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email адміністратора (для відображення) 3')),
                ('admin_phone_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон адміністратора 1')),
                ('admin_phone_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон адміністратора 2')),
                ('admin_phone_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон адміністратора 3')),
                ('operating_mode_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим роботи (укр.)')),
                ('operating_mode_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим роботи (en.)')),
                ('lunch_break_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Перерва (укр.)')),
                ('lunch_break_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Перерва (en.)')),
                ('fb_url', models.URLField(blank=True, null=True, verbose_name='Посилання на Facebook')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Посилання на Youtube')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Посилання на Twitter')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Посилання на Instagram')),
                ('form_email_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email форми 1')),
                ('form_email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email форми 2')),
                ('form_email_3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email форми 3')),
            ],
            options={
                'verbose_name': 'Зміст сторінки',
                'verbose_name_plural': 'Зміст сторінки',
            },
        ),
    ]
