# Generated by Django 2.2.24 on 2021-08-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='consultations_phone_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон консультанта з заявниками 1'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='consultations_phone_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон консультанта з заявниками 2'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='consultations_phone_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон консультанта з заявниками 3'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='consultations_phone_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон консультанта з заявниками 4'),
        ),
    ]
