# Generated by Django 3.2.12 on 2023-02-09 14:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210803_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='content_sidebar_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Зміст бокової панелі (en.)'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='content_sidebar_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Зміст бокової панелі (en.)'),
        ),
    ]
