# Generated by Django 3.2.12 on 2023-02-10 18:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20230209_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactspage',
            name='content_sidebar_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Зміст бокової панелі (укр.)'),
        ),
    ]
