# Generated by Django 2.1.3 on 2020-06-20 18:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title_uk', models.CharField(default='API', max_length=255, verbose_name='Заголовок')),
                ('content_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст')),
                ('title_en', models.CharField(default='API', max_length=255, verbose_name='Заголовок')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст')),
            ],
            options={
                'verbose_name': 'Зміст сторінки "API"',
                'verbose_name_plural': 'Зміст сторінки "API"',
            },
        ),
    ]
