# Generated by Django 2.1.1 on 2018-09-28 11:45

from django.db import migrations, models
import django.db.models.deletion
import sys


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elasticindex',
            options={'ordering': ('field_name',), 'verbose_name': 'Поле ElasticSearch', 'verbose_name_plural': 'Індекс ElasticSearch'},
        ),
        migrations.AlterModelOptions(
            name='ipccode',
            options={'managed': 'test' in sys.argv, 'ordering': ('code_inid',), 'verbose_name': 'Код ІНІД', 'verbose_name_plural': 'Коди ІНІД'},
        ),
        migrations.AlterField(
            model_name='elasticindex',
            name='field_name',
            field=models.CharField(max_length=255, verbose_name='Назва поля у індексі ElasticSearch'),
        ),
        migrations.AlterField(
            model_name='elasticindex',
            name='ipc_codes',
            field=models.ManyToManyField(blank=True, null=True, to='search.IpcCode', verbose_name='ІНІД-коди'),
        ),
        migrations.AlterField(
            model_name='elasticindex',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_type': 'nested'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.ElasticIndex', verbose_name='Батьківське поле (nested)'),
        ),
        migrations.AlterField(
            model_name='simplesearchfields',
            name='elastic_index_fields',
            field=models.ManyToManyField(blank=True, null=True, to='search.ElasticIndex', verbose_name='ІНІД-коди'),
        ),
    ]
