# Generated by Django 2.1.1 on 2018-09-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180928_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticindex',
            name='ipc_codes',
            field=models.ManyToManyField(blank=True, to='search.IpcCode', verbose_name='ІНІД-коди'),
        ),
        migrations.AlterField(
            model_name='simplesearchfields',
            name='elastic_index_fields',
            field=models.ManyToManyField(blank=True, to='search.ElasticIndex', verbose_name='ІНІД-коди'),
        ),
    ]
