# Generated by Django 2.1.1 on 2018-09-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20180928_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElasticIndex',
            new_name='ElasticIndexField',
        ),
        migrations.RenameModel(
            old_name='SimpleSearchFields',
            new_name='SimpleSearchField',
        ),
        migrations.AlterModelOptions(
            name='simplesearchfield',
            options={'ordering': ('field_name',), 'verbose_name': 'Поле форми пошуку', 'verbose_name_plural': 'Поле простої форми пошуку'},
        ),
    ]
