# Generated by Django 2.1.1 on 2018-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20180928_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplesearchfield',
            options={'ordering': ('field_name',), 'verbose_name': 'Поле форми пошуку', 'verbose_name_plural': 'Проста форма пошуку'},
        ),
        migrations.RemoveField(
            model_name='simplesearchfield',
            name='field_label',
        ),
        migrations.AddField(
            model_name='simplesearchfield',
            name='field_label_en',
            field=models.CharField(default='', max_length=255, verbose_name='Label поля (англ.)'),
        ),
        migrations.AddField(
            model_name='simplesearchfield',
            name='field_label_ua',
            field=models.CharField(default='', max_length=255, verbose_name='Label поля (укр.)'),
        ),
        migrations.AlterField(
            model_name='simplesearchfield',
            name='elastic_index_fields',
            field=models.ManyToManyField(blank=True, limit_choices_to={'field_type__in': ('integer', 'keyword', 'text', 'date')}, to='search.ElasticIndexField', verbose_name='Поля ElasticSearch'),
        ),
    ]
