# Generated by Django 2.1.2 on 2018-11-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180928_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticindexfield',
            name='field_type',
            field=models.CharField(choices=[('date', 'Date'), ('integer', 'Integer'), ('keyword', 'Keyword'), ('nested', 'Nested'), ('text', 'Text')], max_length=255, verbose_name='Тип поля ElasticSearch'),
        ),
        migrations.AlterField(
            model_name='elasticindexfield',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_type': 'nested'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.ElasticIndexField', verbose_name='Батьківське поле (nested)'),
        ),
    ]
