# Generated by Django 2.1.3 on 2018-11-20 10:58

from django.db import migrations, models
import sys


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20181102_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpcAppList',
            fields=[
                ('id', models.AutoField(db_column='idAPPNumber', primary_key=True, serialize=False)),
                ('app_number', models.CharField(blank=True, db_column='APP_Number', max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, db_column='RegistrationNumber', max_length=32, null=True)),
                ('registration_date', models.DateTimeField(blank=True, db_column='RegistrationDate', null=True)),
                ('id_shedule_type', models.IntegerField(db_column='idSheduleType')),
                ('files_path', models.CharField(blank=True, db_column='FilesPath', max_length=500, null=True)),
                ('id_parent', models.IntegerField(blank=True, db_column='idParent', null=True)),
                ('id_claim', models.IntegerField(blank=True, db_column='idClaim', null=True)),
                ('idobjtype', models.IntegerField(blank=True, db_column='idObjType', null=True)),
                ('changescount', models.IntegerField(db_column='ChangesCount')),
                ('lastupdate', models.DateTimeField(blank=True, db_column='LastUpdate', null=True)),
                ('idstatus', models.IntegerField(blank=True, db_column='idStatus', null=True)),
                ('app_date', models.DateTimeField(blank=True, db_column='APP_Date', null=True)),
                ('app_input_date', models.DateTimeField(blank=True, db_column='app_input_date', null=True)),
                ('elasticindexed', models.IntegerField(blank=True, db_column='ElasticIndexed', null=True)),
                ('notification_date', models.DateField(blank=True, db_column='NotificationDate', null=True)),
                ('last_indexation_date', models.DateTimeField(blank=True, db_column='last_indexation_date', null=True)),
                ('in_electronic_bull', models.BooleanField(blank=True, db_column='in_electronic_bull', null=True)),
                ('publication_app_date', models.DateTimeField(blank=True, db_column='publication_APP_date', null=True)),
                ('is_limited', models.BooleanField(db_column='is_limited', default=False)),
            ],
            options={
                'db_table': 'IPC_AppList',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.RemoveField(
            model_name='elasticindexfield',
            name='ipc_codes',
        ),
    ]
