# Generated by Django 2.1.3 on 2018-12-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import sys


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20181120_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDocuments',
            fields=[
                ('id', models.AutoField(db_column='idDocument', primary_key=True, serialize=False)),
                ('enter_num', models.IntegerField(db_column='enterNum')),
                ('add_date', models.DateTimeField(db_column='AddDate')),
                ('file_name', models.CharField(blank=True, db_column='FileName', max_length=500, null=True)),
                ('file_type', models.CharField(blank=True, db_column='FileType', max_length=10, null=True)),
                ('barcode', models.CharField(blank=True, db_column='BarCODE', max_length=50, null=True)),
                ('cead_id_doc', models.IntegerField(blank=True, db_column='CEADIdDoc', null=True)),
            ],
            options={
                'db_table': 'APP_Documents',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.AutoField(db_column='idOrderDoc', primary_key=True, serialize=False)),
                ('id_cead_doc', models.IntegerField(blank=True, db_column='idCEADDoc', null=True)),
                ('file_type', models.CharField(blank=True, db_column='FileType', max_length=20, null=True)),
                ('file_size', models.IntegerField(blank=True, db_column='FileSize', null=True)),
            ],
            options={
                'db_table': 'ls_OrderDocuments',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.AutoField(db_column='idOrder', primary_key=True, serialize=False)),
                ('ip_user', models.GenericIPAddressField(blank=True, db_column='IP_User', null=True)),
                ('order_completed', models.BooleanField(blank=True, db_column='OrderCompleted', null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, db_column='CompletionDateTime', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreateDateTime')),
            ],
            options={
                'db_table': 'ls_OrderService',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.AlterModelOptions(
            name='inidcodeschedule',
            options={'managed': 'test' in sys.argv, 'verbose_name': 'Пошуковий параметр', 'verbose_name_plural': 'Пошукові параметри'},
        ),
        migrations.AlterModelOptions(
            name='scheduletype',
            options={'managed': 'test' in sys.argv, 'verbose_name': 'Реєстр', 'verbose_name_plural': 'Реєстри'},
        ),
        migrations.RemoveField(
            model_name='simplesearchfield',
            name='elastic_index_fields',
        ),
        migrations.AddField(
            model_name='simplesearchfield',
            name='elastic_index_field',
            field=models.ForeignKey(blank=True, db_column='ElasticIndexField', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.ElasticIndexField', verbose_name='Поле індексу ElasticSearch'),
        ),
    ]
