# Generated by Django 2.1.3 on 2018-12-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20181222_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplesearchfield',
            options={'ordering': ('id',), 'verbose_name': 'Поле форми пошуку', 'verbose_name_plural': 'Проста форма пошуку'},
        ),
        migrations.RemoveField(
            model_name='simplesearchfield',
            name='field_name',
        ),
    ]
