# Generated by Django 2.1.3 on 2018-12-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20181222_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplesearchfield',
            name='weight',
            field=models.PositiveIntegerField(default=1000, help_text='Чим більша вага, тим вище параметр пошуку у списку', verbose_name='Вага'),
        ),
    ]
