# Generated by Django 2.1.3 on 2019-01-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_simplesearchfield_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexationError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('json_path', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(db_column='idAPPNumber', on_delete=django.db.models.deletion.CASCADE, to='search.IpcAppList')),
            ],
        ),
    ]
