# Generated by Django 2.1.3 on 2019-04-17 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_indexationerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Назва параметру (укр.)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Назва параметру (en.)')),
                ('value', models.CharField(max_length=255, unique=True, verbose_name='Значення поля')),
                ('ordering', models.CharField(choices=[('asc', 'По зростанню'), ('desc', 'За спаданням')], max_length=4, verbose_name='Напрямок сортування')),
                ('weight', models.PositiveIntegerField(default=1000, help_text='Чим більша вага, тим вище елемент у списку параметрів на сторінках результатів пошуку.', verbose_name='Вага')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Відображати')),
                ('search_field', models.ForeignKey(blank=True, help_text='Пошуковий параметр, по якому відбувається сортування.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.SimpleSearchField', verbose_name='Пошуковий параметр')),
            ],
            options={
                'verbose_name': 'Параметр сортування',
                'verbose_name_plural': 'Параметри сортування результатів пошуку',
            },
        ),
    ]
