# Generated by Django 2.1.3 on 2019-04-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_sortparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexationProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_indexed_count', models.PositiveIntegerField(default=0, verbose_name="Кількість об'єктів для індексації")),
                ('processed_count', models.PositiveIntegerField(default=0, verbose_name="Опрацьовано об'єктів")),
                ('begin_date', models.DateTimeField(verbose_name='Дата та час початку індексації')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата та час закінчення індексації')),
            ],
            options={
                'verbose_name': 'Процес індексації',
                'verbose_name_plural': 'Процеси індексації',
            },
        ),
        migrations.AddField(
            model_name='indexationerror',
            name='correction_count',
            field=models.IntegerField(db_column='correctionCount', default=0),
        ),
        migrations.AddField(
            model_name='indexationerror',
            name='error_last_update',
            field=models.DateTimeField(blank=True, db_column='errLastUpdate', null=True),
        ),
        migrations.AddField(
            model_name='indexationerror',
            name='error_status',
            field=models.CharField(blank=True, db_column='errStatus', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='indexationerror',
            name='indexation_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.IndexationProcess'),
        ),
    ]
