# Generated by Django 2.1.3 on 2019-10-10 13:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_auto_20191010_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplesearchpage',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис сторінки (англ.)'),
        ),
        migrations.AlterField(
            model_name='simplesearchpage',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис сторінки (укр.)'),
        ),
    ]
