# Generated by Django 2.1.3 on 2020-02-19 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0018_appuseraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.IpcAppList', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Перегляд заявки користувачем',
                'verbose_name_plural': 'Перегляди заявок користувачами',
            },
        ),
    ]
