# Generated by Django 2.1.3 on 2020-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_auto_20200219_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidServicesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_app_access_price', models.DecimalField(decimal_places=2, default=120, max_digits=8, verbose_name='Вартість доступу до заявки на ТМ')),
            ],
        ),
    ]
