# Generated by Django 2.1.3 on 2020-02-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_paidservicessettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paidservicessettings',
            options={'verbose_name': 'Налаштування платних послуг', 'verbose_name_plural': 'Налаштування платних послуг'},
        ),
        migrations.AlterField(
            model_name='paidservicessettings',
            name='tm_app_access_price',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=8, verbose_name='Вартість доступу до заявки на ТМ, грн'),
        ),
    ]
