# Generated by Django 2.1.3 on 2020-03-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_auto_20200220_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidservicessettings',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Увімкнено'),
        ),
    ]
