# Generated by Django 2.1.3 on 2020-06-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_ipccodeobjtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipccodeobjtype',
            options={'verbose_name_plural': "Типи об'єктів"},
        ),
        migrations.AlterField(
            model_name='ipccodeobjtype',
            name='ipc_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.IpcCode', verbose_name='Код ІНІД'),
        ),
        migrations.AlterField(
            model_name='ipccodeobjtype',
            name='obj_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.ObjType', verbose_name="Тип об'єкту"),
        ),
    ]
