# Generated by Django 4.1.7 on 2023-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_auto_20200611_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDateCead',
            fields=[
                ('id', models.AutoField(db_column='idDelivery', primary_key=True, serialize=False)),
                ('id_doc_cead', models.IntegerField(blank=True, db_column='idDoc', null=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('valid_send_date', models.BooleanField(blank=True, null=True)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('valid_receive_date', models.BooleanField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('valid_return_date', models.BooleanField(blank=True, null=True)),
                ('return_why', models.CharField(blank=True, max_length=300, null=True)),
                ('iddoc_techn_sys', models.IntegerField(blank=True, null=True)),
                ('date_send_to_cancelary', models.DateTimeField(blank=True, null=True)),
                ('is_error', models.CharField(blank=True, max_length=250, null=True)),
                ('exchange_command', models.CharField(blank=True, max_length=250, null=True)),
                ('is_worked_techsys', models.IntegerField(blank=True, null=True)),
                ('is_electronic', models.IntegerField(blank=True, null=True)),
                ('is_bug', models.IntegerField(blank=True, null=True)),
                ('retread_date', models.DateTimeField(blank=True, null=True)),
                ('retread_why', models.CharField(blank=True, max_length=250, null=True)),
                ('manual_insert', models.IntegerField(blank=True, null=True)),
                ('exported_441_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ls_delivery_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FvCicImporter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('claim_id', models.BigIntegerField()),
                ('claim_number', models.CharField(blank=True, max_length=30, null=True)),
                ('claim_od_number', models.CharField(blank=True, max_length=30, null=True)),
                ('is_censored', models.TextField(blank=True, null=True)),
                ('claim_state', models.BigIntegerField()),
                ('app_set_date', models.DateTimeField(blank=True, null=True)),
                ('app_input_date', models.DateTimeField()),
                ('od_publication_date', models.DateTimeField(blank=True, null=True)),
                ('json_cic', models.TextField(blank=True, null=True)),
                ('json_files_info', models.TextField(blank=True, null=True)),
                ('is_exported', models.TextField(blank=True, null=True)),
                ('is_exported_datetime', models.DateTimeField(blank=True, null=True)),
                ('type_code', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'fv_cic_importer',
                'managed': False,
            },
        ),
    ]
