# Generated by Django 4.1.7 on 2024-04-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_deliverydatecead_fvcicimporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLimited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('app_number', models.CharField(db_index=True, max_length=16, verbose_name='Номер заявки')),
                ('obj_type', models.ForeignKey(blank=True, db_column='idObjType', null=True, on_delete=django.db.models.deletion.CASCADE, to='search.objtype', verbose_name="Тип об'єкта")),
            ],
            options={
                'db_table': 'ls_limited_applications',
            },
        ),
    ]
