# Generated by Django 4.1.7 on 2024-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_applimited'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applimited',
            constraint=models.UniqueConstraint(fields=('app_number', 'obj_type'), name='unique app_number_obj_type'),
        ),
    ]
