# Generated by Django 4.1.7 on 2024-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_applimited_unique app_number_obj_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applimited',
            options={'verbose_name': 'Обмежена публікація', 'verbose_name_plural': 'Обмежені публікації'},
        ),
        migrations.AddField(
            model_name='applimited',
            name='settings_json',
            field=models.TextField(blank=True, null=True, verbose_name='Налаштування'),
        ),
    ]
