# Generated by Django 4.1.7 on 2024-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_alter_applimited_options_applimited_settings_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='applimited',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина обмеження даних'),
        ),
        migrations.AlterField(
            model_name='applimited',
            name='settings_json',
            field=models.TextField(blank=True, help_text='Налаштування публікації у форматі JSON', null=True, verbose_name='Налаштування'),
        ),
    ]
