# Generated by Django 4.1.7 on 2024-05-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_applimited_reason_alter_applimited_settings_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applimited',
            name='settings_json',
            field=models.TextField(blank=True, default='{}', help_text='Налаштування публікації у форматі JSON', null=True, verbose_name='Налаштування'),
        ),
    ]
