# Generated by Django 4.1.7 on 2024-08-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0031_alter_applimited_settings_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexationprocess',
            name='documents_in_index_shared',
        ),
        migrations.DeleteModel(
            name='AppUserAccess',
        ),
    ]
