# Generated by Django 4.1.7 on 2024-08-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0032_remove_indexationprocess_documents_in_index_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applimited',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='Обмеження зняті',
                                      help_text='Якщо опцію активовано, то дані об\'єкта відображатимуться '
                                                'у повному обсязі'),
        ),
        migrations.AlterField(
            model_name='applimited',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина обмеження даних / зняття обмежень'),
        ),
    ]
