# Generated by Django 2.1.3 on 2020-03-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0002_auto_20200312_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_request_pb_xml',
            field=models.TextField(blank=True, null=True, verbose_name='XML запиту ПБ після запису платежа'),
        ),
    ]
