# Generated by Django 4.1.7 on 2023-03-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0004_auto_20200313_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
