# Generated by Django 4.1.7 on 2024-08-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_attorneys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentAttorneyExt',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('reg_num', models.IntegerField(blank=True, db_column='Reg_Num', null=True)),
                ('dat_reg', models.DateTimeField(blank=True, db_column='Dat_Reg', null=True)),
                ('prizv', models.CharField(blank=True, db_column='Prizv', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('po_batk', models.CharField(blank=True, db_column='Po_Batk', max_length=50, null=True)),
                ('sex', models.BooleanField(blank=True, db_column='SEX', null=True)),
                ('dat_at_kom', models.DateTimeField(blank=True, db_column='Dat_At_Kom', null=True)),
                ('num_at_kom', models.IntegerField(blank=True, db_column='Num_At_Kom', null=True)),
                ('special', models.CharField(blank=True, db_column='Special', max_length=500, null=True)),
                ('postaladdress', models.CharField(blank=True, db_column='PostalAddress', max_length=255, null=True)),
                ('phones', models.CharField(blank=True, db_column='Phones', max_length=300, null=True)),
                ('e_mail', models.CharField(blank=True, db_column='E_Mail', max_length=300, null=True)),
                ('mis_rob', models.CharField(blank=True, db_column='Mis_Rob', max_length=450, null=True)),
                ('public_orgs', models.TextField(blank=True, db_column='PublicOrgs', max_length=8000, null=True)),
                ('event_list', models.TextField(blank=True, db_column='EventList', max_length=8000, null=True)),
                ('competence_list', models.TextField(blank=True, db_column='CompetenceList', max_length=8000, null=True)),
                ('sanctions_list', models.TextField(blank=True, db_column='SanctionsList', max_length=8000, null=True)),
                ('last_update', models.DateTimeField(blank=True, db_column='LastUpdate', null=True)),
            ],
            options={
                'db_table': 'patent_attorneys_ext',
                'ordering': ('reg_num',),
            },
        ),
    ]
