# Generated by Django 4.1.7 on 2025-10-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_attorneys', '0003_patentattorneynew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentattorneynew',
            name='pat_id',
            field=models.BigIntegerField(blank=True, db_column='Pat_ID', null=True),
        ),
    ]
