# Generated by Django 4.1.7 on 2025-10-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent_attorneys', '0004_alter_patentattorneynew_pat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentattorneynew',
            name='sex',
            field=models.CharField(blank=True, db_column='SEX', max_length=16, null=True),
        ),
    ]
