# Generated by Django 2.2.17 on 2021-05-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0025_auto_20200611_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва групи')),
                ('obj_state', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Заявка'), (2, 'Охоронний документ')], null=True, verbose_name="Стан об'єкта")),
                ('obj_types', models.ManyToManyField(blank=True, to='search.ObjType', verbose_name="Типи об'єктів")),
            ],
            options={
                'verbose_name': 'Група сборів',
                'verbose_name_plural': 'Групи сборів',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип збору')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Group')),
            ],
            options={
                'verbose_name': 'Вид сбору',
                'verbose_name_plural': 'Види сборів',
            },
        ),
    ]
