# Generated by Django 2.2.17 on 2021-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210520_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Назва збору'),
        ),
    ]
