# Generated by Django 2.2.17 on 2021-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210525_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='title_uk',
            field=models.CharField(max_length=1024, verbose_name='Назва збору (укр.)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Назва групи (укр.)'),
        ),
    ]
