# Generated by Django 2.2.17 on 2021-05-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20210525_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('app_number', models.CharField(max_length=32, verbose_name='Номер заявки')),
                ('value', models.PositiveIntegerField(verbose_name='Сума платежу')),
                ('fee_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.FeeType', verbose_name='Вид сбору')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('code', models.SmallIntegerField(choices=[(1, 'Успішно оплачен'), (2, 'Помилка при оплаті')], help_text='1 - успішно оплачено, 2 - помилка при оплаті', verbose_name='Код операції')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Операція по замовленню',
                'verbose_name_plural': 'Операції по замовленням',
            },
        ),
    ]
