# Generated by Django 2.2.17 on 2021-05-28 09:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_order_orderoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис сторінки (укр.)')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис сторінки (англ.)')),
            ],
            options={
                'verbose_name': 'Інформація на сторінці формування замовлення',
                'verbose_name_plural': 'Інформація на сторінці формування замовлення',
            },
        ),
    ]
