# Generated by Django 2.2.17 on 2021-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('weight',), 'verbose_name': 'Група сборів', 'verbose_name_plural': 'Групи сборів'},
        ),
        migrations.AddField(
            model_name='group',
            name='weight',
            field=models.IntegerField(blank=True, default=999, help_text='Чим більше вага, тим вище елемент у списку', null=True, verbose_name='Вага'),
        ),
    ]
