# Generated by Django 2.2.17 on 2021-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20210528_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='weight',
            field=models.IntegerField(default=999, help_text='Чим більше вага, тим вище елемент у списку', verbose_name='Вага'),
        ),
    ]
