# Generated by Django 2.2.17 on 2021-05-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20210528_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-weight',), 'verbose_name': 'Група сборів', 'verbose_name_plural': 'Групи сборів'},
        ),
        migrations.AddField(
            model_name='orderoperation',
            name='pay_request_pb_xml',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Запит PrivatBank24'),
        ),
        migrations.AddField(
            model_name='orderoperation',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Сума платежу'),
        ),
    ]
