# Generated by Django 2.2.17 on 2021-06-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20210531_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='needs_app_number',
            field=models.BooleanField(default=True, verbose_name='Потребує номера заявки'),
        ),
    ]
