# Generated by Django 2.2.17 on 2021-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_feetype_needs_app_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='app_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='orderoperation',
            name='code',
            field=models.SmallIntegerField(choices=[(1, 'Успішно сплачено'), (2, 'Помилка при сплаті')], help_text='1 - успішно сплачено, 2 - помилка при сплаті', verbose_name='Код операції'),
        ),
    ]
