# Generated by Django 2.2.24 on 2021-07-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20210618_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Код платіжної групи')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Платіжна група послуги',
                'verbose_name_plural': 'Платіжні групи послуг',
            },
        ),
        migrations.AddField(
            model_name='feetype',
            name='service_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.ServiceGroup'),
        ),
    ]
