# Generated by Django 2.2.24 on 2021-07-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20210706_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Увімкнено (доступний для платежу)'),
        ),
    ]
