# Generated by Django 3.2.12 on 2022-11-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_feetype_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_form',
            field=models.BooleanField(default=True, verbose_name='Відображати форму для платежу'),
        )
    ]
