# Generated by Django 2.2.17 on 2021-02-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0025_auto_20200611_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(db_column='idBull', primary_key=True, serialize=False)),
                ('bul_date', models.DateField(blank=True, db_column='Bull_Date', null=True)),
                ('date_from', models.DateField(blank=True, db_column='Date_from', null=True)),
                ('date_to', models.DateField(blank=True, db_column='Date_to', null=True)),
                ('bul_number', models.IntegerField(blank=True, db_column='Bull_Number', null=True)),
            ],
            options={
                'db_table': 'cl_list_official_bulletins_ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EBulletinData',
            fields=[
                ('id', models.AutoField(db_column='id_object', primary_key=True, serialize=False)),
                ('app_number', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ls_SIS_ebulletin_data_new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EBulletinUnit',
            fields=[
                ('id', models.AutoField(db_column='id_unit', primary_key=True, serialize=False)),
                ('unit_name_ua', models.CharField(blank=True, max_length=500, null=True)),
                ('unit_name_en', models.CharField(blank=True, max_length=500, null=True)),
                ('view_order', models.IntegerField(blank=True, null=True)),
                ('sql_query', models.TextField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cl_ebulletin_units_new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EBulletinUnitHeader',
            fields=[
                ('id', models.AutoField(db_column='id_header', primary_key=True, serialize=False)),
                ('header_ua', models.CharField(blank=True, max_length=500, null=True)),
                ('header_en', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'cl_bulletin_unit_headers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Тип сповіщення')),
                ('obj_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.ObjType', verbose_name='Тип ОПВ')),
            ],
            options={
                'db_table': 'bulletin_transaction_type',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField(verbose_name='Дані сповіщення у форматі JSON.')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_new.Bulletin', verbose_name='Тип ОПВ')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_new.TransactionType', verbose_name='Тип сповіщення')),
            ],
            options={
                'db_table': 'bulletin_transaction',
            },
        ),
    ]
