# Generated by Django 2.0.7 on 2018-07-19 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Підтверджено')),
                ('pszIssuer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ім’я ЦСК, що видав сертифікат')),
                ('pszIssuerCN', models.CharField(blank=True, max_length=255, null=True, verbose_name='Реквізити ЦСК, що видав сертифікат')),
                ('pszSerial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Реєстраційний номер сертифіката')),
                ('pszSubject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ім’я власника сертифіката')),
                ('pszSubjCN', models.CharField(blank=True, max_length=255, null=True, verbose_name='Реквізити власника сертифіката')),
                ('pszSubjOrg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Організація до якої належить власник сертифіката')),
                ('pszSubjOrgUnit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Підрозділ організації до якої належить власник сертифіката')),
                ('pszSubjTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Посада власника сертифіката')),
                ('pszSubjState', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва області до якої належить власник сертифіката')),
                ('pszSubjFullName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Повне ім’я власника сертифіката')),
                ('pszSubjAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса власника сертифіката')),
                ('pszSubjPhone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефону власника сертифіката')),
                ('pszSubjEMail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса електронної пошти власника сертифіката')),
                ('pszSubjDNS', models.CharField(blank=True, max_length=255, null=True, verbose_name='DNS-ім`я чи інше технічного засобу')),
                ('pszSubjEDRPOUCode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код ЄДРПОУ власника сертифіката')),
                ('pszSubjDRFOCode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код ДРФО власника сертифіката')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Web-адреса')),
                ('ocspAccessPointAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='OCSP-сервер')),
                ('ocspAccessPointPort', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порт OCSP-сервера')),
                ('cmpAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='CMP-сервер')),
                ('tspAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='TSP-сервер')),
                ('tspAddressPort', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порт TSP-сервера')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
