# Generated by Django 2.1.1 on 2018-09-28 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_auto_20180720_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateowner',
            options={'verbose_name': 'Сертифікат', 'verbose_name_plural': 'Сертифікати'},
        ),
        migrations.AlterField(
            model_name='certificateowner',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено та поле "Користувач" не заповнено, то буде створено нового користувача', verbose_name='Підтверджено'),
        ),
        migrations.AlterField(
            model_name='certificateowner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
