# Generated by Django 2.1.3 on 2019-05-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_auto_20180928_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateowner',
            name='is_confirmed',
        ),
    ]
