# Generated by Django 4.1.7 on 2023-03-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0005_patentattorney'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyCenter',
        ),
    ]
