# Generated by Django 2.1.3 on 2020-02-14 08:55

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Значення')),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Баланс рахунку',
                'verbose_name_plural': 'Баланси рахунків',
            },
        ),
    ]
