# Generated by Django 2.1.3 on 2020-02-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_auto_20200219_1224'),
        ('account', '0002_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Значення')),
                ('type', models.IntegerField(choices=[(1, 'Надання доступу до інформації про заявку'), (2, 'Поповнення')], verbose_name='Тип операції')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.IpcAppList', verbose_name='Заявка')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Balance', verbose_name='Рахунок')),
            ],
            options={
                'verbose_name': 'Операція з балансом рахунку',
                'verbose_name_plural': 'Операції з балансом рахунків',
            },
        ),
    ]
