# Generated by Django 2.1.3 on 2020-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_balanceoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperation',
            name='type',
            field=models.IntegerField(choices=[(1, 'Надання доступу до інформації про заявку'), (2, 'Поповнення рахунку')], verbose_name='Тип операції'),
        ),
    ]
