# Generated by Django 2.1.3 on 2020-02-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Системне повідомлення', 'verbose_name_plural': 'Системні повідомлення'},
        ),
        migrations.AddField(
            model_name='message',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
    ]
