# Generated by Django 4.1.7 on 2024-01-03 13:53

from django.db import migrations, models
import django.db.models.deletion
import sys


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WKMMark',
            fields=[
                ('id', models.AutoField(db_column='IdMark', primary_key=True, serialize=False)),
                ('decision_date', models.DateTimeField(db_column='DecisionDate')),
                ('order_date', models.DateTimeField(db_column='OrderDate')),
                ('order_number', models.CharField(db_column='OrderNumber', max_length=50)),
                ('rights_date', models.DateTimeField(db_column='RightsDate')),
                ('keywords', models.CharField(blank=True, db_column='KeyWords', max_length=200, null=True)),
                ('mark_image', models.BinaryField(blank=True, db_column='MarkImage', max_length='max', null=True)),
                ('state_id', models.SmallIntegerField(db_column='IdState')),
                ('where_to_publish', models.CharField(db_column='wheretopublish', max_length=20)),
                ('court_comments_ua',
                 models.CharField(blank=True, db_column='courtcomments', max_length=255, null=True)),
                ('court_comments_rus',
                 models.CharField(blank=True, db_column='courtcommentsRUS', max_length=255, null=True)),
                ('court_comments_eng',
                 models.CharField(blank=True, db_column='courtcommentsENG', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Mark',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.CreateModel(
            name='WKMRefBulletin',
            fields=[
                ('id', models.AutoField(db_column='IdBulletin', primary_key=True, serialize=False)),
                ('bulletin_date', models.DateTimeField(db_column='BulletinDate')),
                ('bulletin_number', models.CharField(db_column='BulletinNumber', max_length=50)),
                ('bull_str', models.CharField(blank=True, db_column='bullStr', max_length=10, null=True)),
            ],
            options={
                'db_table': 'ref_Bulletins',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.CreateModel(
            name='WKMRefOwner',
            fields=[
                ('id', models.AutoField(db_column='IdOwner', primary_key=True, serialize=False)),
                ('owner_name', models.CharField(db_column='OwnerName', max_length=500)),
                ('country_code', models.CharField(db_column='CountryCode', max_length=2)),
            ],
            options={
                'db_table': 'ref_Owners',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.CreateModel(
            name='WKMMarkOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.SmallIntegerField(db_column='OrdNum')),
                ('mark', models.ForeignKey(db_column='IdMark', on_delete=django.db.models.deletion.DO_NOTHING,
                                           to='wkmmark')),
                ('owner', models.ForeignKey(db_column='IdOwner', on_delete=django.db.models.deletion.DO_NOTHING,
                                            to='wkmrefowner')),
            ],
            options={
                'db_table': 'MarkOwners',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.AddField(
            model_name='wkmmark',
            name='bulletin',
            field=models.ForeignKey(blank=True, db_column='IdBulletin', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='wkmrefbulletin'),
        ),
        migrations.AddField(
            model_name='wkmmark',
            name='owners',
            field=models.ManyToManyField(through='WKMMarkOwner', to='wkm.wkmrefowner'),
        ),
        migrations.CreateModel(
            name='WKMClass',
            fields=[
                ('class_number', models.SmallIntegerField(db_column='ClassNumber')),
                ('ord_num', models.SmallIntegerField(db_column='OrdNum')),
                ('products', models.CharField(db_column='Products', max_length=2000)),
                ('mark', models.ForeignKey(db_column='IdMark', on_delete=django.db.models.deletion.DO_NOTHING,
                                           to='wkmmark')),
            ],
            options={
                'db_table': 'MarkProducts',
                'managed': 'test' in sys.argv
            },
        ),
        migrations.CreateModel(
            name='WKMVienna',
            fields=[
                ('class_number', models.CharField(db_column='ClassNumber', max_length=255)),
                ('mark', models.ForeignKey(db_column='IdMark', on_delete=django.db.models.deletion.DO_NOTHING,
                                           to='wkmmark')),
            ],
            options={
                'db_table': 'MarkVienna',
                'managed': 'test' in sys.argv
            },
        ),
    ]

    def __init__(self, name, app_label):
        super(Migration, self).__init__(name, app_label)
