# Generated by Django 4.1.7 on 2024-09-06 13:08

import sys
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wkm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WKMDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Код типу документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типи документів',
                'db_table': 'ref_DocumentTypes',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.CreateModel(
            name='WKMDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.BinaryField(blank=True, editable=True, max_length='max', null=True, verbose_name='Файл')),
                ('document_type', models.ForeignKey(
                    'wkm.WKMDocumentType',
                    on_delete=models.SET_NULL,
                    verbose_name='Тип документа',
                    null=True,
                    db_column='IdDocumentType'
                )),
                ('wkm', models.ForeignKey(
                    'wkm.WKMMark',
                    on_delete=models.SET_NULL,
                    verbose_name='Тип документа',
                    null=True,
                    db_column='idMark'
                )),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
                'db_table': 'MarkDocuments',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.AlterModelOptions(
            name='wkmclass',
            options={'managed': 'test' in sys.argv, 'verbose_name': 'Клас', 'verbose_name_plural': 'Ніццька класифікація'},
        ),
        migrations.AlterModelOptions(
            name='wkmmark',
            options={'managed': 'test' in sys.argv, 'verbose_name': 'Добре відома ТМ', 'verbose_name_plural': 'Добре відомі ТМ'},
        ),
        migrations.AlterModelOptions(
            name='wkmmarkowner',
            options={'managed': 'test' in sys.argv, 'verbose_name': 'Власник', 'verbose_name_plural': 'Власники'},
        ),
        migrations.AlterModelOptions(
            name='wkmrefbulletin',
            options={'managed': 'test' in sys.argv, 'verbose_name': 'Бюлетень', 'verbose_name_plural': 'Список бюлетенів'},
        ),
        migrations.AlterModelOptions(
            name='wkmrefowner',
            options={'managed': 'test' in sys.argv, 'ordering': ('owner_name',), 'verbose_name': 'Власник', 'verbose_name_plural': 'Власники'},
        ),
        migrations.AlterModelOptions(
            name='wkmvienna',
            options={'managed': 'test' in sys.argv, 'verbose_name': 'Клас', 'verbose_name_plural': 'Віденська класифікація'},
        ),
    ]
