# Generated by Django 2.1.3 on 2019-03-18 09:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='content',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='help',
            old_name='title',
            new_name='title_uk',
        ),
        migrations.AddField(
            model_name='help',
            name='content_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст'),
        ),
        migrations.AddField(
            model_name='help',
            name='title_en',
            field=models.CharField(default='Help', max_length=255, verbose_name='Заголовок'),
        ),
    ]
