# Generated by Django 2.1.3 on 2019-10-24 08:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20190318_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст')),
                ('slug', models.SlugField(verbose_name='Ідентифікатор для URL')),
                ('weight', models.PositiveIntegerField(default=1000, help_text='Чим більша вага, тим вище на сторінці цей розділ', verbose_name='Вага')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст')),
                ('slug', models.SlugField(verbose_name='Ідентифікатор для URL')),
                ('weight', models.PositiveIntegerField(default=1000, help_text='Чим більша вага, тим вище на сторінці цей розділ', verbose_name='Вага')),
            ],
            options={
                'verbose_name': 'Розділ',
                'verbose_name_plural': 'Розділи',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='help.Section'),
        ),
    ]
