# Generated by Django 2.1.3 on 2019-10-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_auto_20191024_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='content_uk',
        ),
    ]
