# Generated by Django 2.1.3 on 2019-10-29 13:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0005_auto_20191024_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст англ.'),
        ),
        migrations.AlterField(
            model_name='help',
            name='content_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст укр.'),
        ),
        migrations.AlterField(
            model_name='help',
            name='title_en',
            field=models.CharField(default='Help', max_length=255, verbose_name='Заголовок англ.'),
        ),
        migrations.AlterField(
            model_name='help',
            name='title_uk',
            field=models.CharField(default='Допомога', max_length=255, verbose_name='Заголовок укр.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст англ.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Зміст укр.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Питання без розділу не відображаються', null=True, on_delete=django.db.models.deletion.SET_NULL, to='help.Section', verbose_name='Розділ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ідентифікатор для URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок англ.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок укр.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ідентифікатор для URL'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок англ.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_uk',
            field=models.CharField(max_length=255, verbose_name='Заголовок укр.'),
        ),
    ]
