# Generated by Django 2.1.3 on 2020-08-30 18:25

import ckeditor_uploader.fields
from django.db import migrations, models
import sys


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EBulletinData',
            fields=[
                ('id', models.AutoField(db_column='idObject', primary_key=True, serialize=False)),
                ('app_number', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.IntegerField(db_column='idUnit', blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ls_SIS_ebulletin_data',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.CreateModel(
            name='EBulletinUnits',
            fields=[
                ('id', models.AutoField(db_column='idUnit', primary_key=True, serialize=False)),
                ('unit_name', models.CharField(blank=True, db_column='UnitName', max_length=300, null=True)),
                ('view_order', models.IntegerField(blank=True, null=True)),
                ('obj_type', models.IntegerField(db_column='idObjType')),
            ],
            options={
                'db_table': 'cl_ebulletin_units',
                'managed': 'test' in sys.argv,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис сторінки (укр.)')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис сторінки (англ.)')),
            ],
            options={
                'verbose_name': 'Дані сторінки',
                'verbose_name_plural': 'Дані сторінки',
            },
        ),
    ]
