# Generated by Django 2.2.17 on 2021-02-11 13:16

from django.db import migrations, models
import sys


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClListOfficialBulletinsIp',
            fields=[
                ('id', models.AutoField(db_column='idBull', primary_key=True, serialize=False)),
                ('bul_date', models.DateField(blank=True, db_column='Bull_Date', null=True)),
                ('date_from', models.DateField(blank=True, db_column='Date_from', null=True)),
                ('date_to', models.DateField(blank=True, db_column='Date_to', null=True)),
                ('bul_number', models.IntegerField(blank=True, db_column='Bull_Number', null=True)),
            ],
            options={
                'db_table': 'cl_list_official_bulletins_ip',
                'managed': 'test' in sys.argv,
            },
        ),
    ]
